# Generated by Django 3.2.8 on 2021-12-01 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211021_1928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-date_posted',)},
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
